# Generated by Django 5.0.3 on 2024-03-12 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('conta_id', models.IntegerField()),
                ('valor', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('forma_pagamento', models.CharField(choices=[('P', 'Pix'), ('C', 'CreditCard'), ('D', 'DebitCard')], max_length=1)),
                ('valor_fee', models.FloatField()),
                ('valor_total', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.account')),
            ],
        ),
    ]
