# Generated by Django 5.0.3 on 2024-03-12 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='conta_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conta', to='bank.account'),
        ),
    ]
